# Generated by Django 4.2.14 on 2024-07-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_coffeemenu_order_orderitem_order_items_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='Is customer'),
        ),
    ]
