# Generated by Django 4.2.14 on 2024-07-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
