# Generated by Django 4.2.14 on 2024-07-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=True, verbose_name='Is customer'),
        ),
    ]
