# Generated by Django 4.2.14 on 2024-07-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeemenu',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
