# Generated by Django 4.2.14 on 2024-07-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_coffeemenu_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeemenu',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
