# Generated by Django 4.2.14 on 2024-07-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_table_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='res',
            field=models.BooleanField(default=False),
        ),
    ]
